# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180515_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
    ]
