# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-29 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180529_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('describe', models.CharField(help_text='不超过200字', max_length=200, verbose_name='站点描述')),
                ('keyword', models.CharField(help_text='以,间隔', max_length=100, verbose_name='关键字')),
                ('beian', models.CharField(max_length=32, verbose_name='备案号')),
            ],
        ),
        migrations.AlterModelOptions(
            name='classify',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
    ]
