# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-29 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180529_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '站点信息', 'verbose_name_plural': '站点信息'},
        ),
        migrations.AlterModelTable(
            name='info',
            table='info',
        ),
    ]
