# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-03 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180602_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(auto_created=True, blank=True, default='/upload/article/common.jpg', help_text='大小200*200，不超过200k', null=True, upload_to='./article/', verbose_name='缩略图')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
            ],
        ),
    ]
